default: &default
  database: pact_broker
  username: pact_broker
  password: pact_broker
  encoding: utf8

test:
  default:
    adapter: sqlite
    database: tmp/pact_broker_database_test.sqlite3
  postgres:
    <<: *default
    adapter: postgres
  mysql:
    <<: *default
    adapter: mysql2

development:
  default:
    adapter: sqlite
    database: db/pact_broker_database.sqlite3
  postgres:
    <<: *default
    adapter: postgres
  mysql:
    <<: *default
    adapter: mysql2

production:
  default:
    <<: *default
    adapter: postgres